### ISSUE TITLE
Etherscan links for stake transactions

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#273]
I was expecting to be able to drill down to Etherscan on my existing stakes. This gets a little messy for stakes that I extend because they're not 1:1. The same is also true for veOGV airdrop claims, which are like 4:1. I think it might make sense to have an expandable detail row for each blockchain transaction associated with each stake. So some stakes might have several associated transactions if they've been extended, and some stakes might each have the same associated transaction linked (redundantly) if they were all part of one claim.

**Comment by tomhirst** [comment]
Yep, it's easy for this to become confusing because we have several transactions related to a single staking (or claiming) action. I like your proposal to have a drop-down expander that within lists all related transactions + links to Etherscan.

We are storing stakes in the database anyway, so what we could do, is save an array of transaction addresses to each stake. 

A couple of potential technical thoughts:

1. When the `extend` contract method is called it unstakes the existing stake and then creates a new one. The event listener is creating/deleting stakes in the database by listening to the "Stake" and "Unstake" events to completely remove and re-add user-specific stakes on extension. If we want to retain an ongoing array of transaction addresses, we won't be able to delete a stake and re-add it as we do now. We'll need to re-factor the listener. This might not be straightforward given the event ordering of the contract method. 

2. We would need to run the listener back from the block that the staking contract was created to back-fill the database with transaction data from previous staking and unstaking events. Users may see some oddities in the staking section of the dApp during this time.
