### ISSUE TITLE
Proposal monitoring

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#294]
@franckc pointed out that we need to alert ourselves anytime a proposal is submitted once governance is fully decentralized. We already have a listener that surfaces proposals in the DApp, but we don't want to rely on this or ourselves to check it often enough to catch anything that we wouldn't want to pass. We should probably wire up the listener to Discord and @mention the OUSD team like we do for Compound governance. It might also be nice to surface this as a feature for users to subscribe to email notifications at some point once there is growing interest in participating.

**Comment by franckc** [comment]
It is critical for the community our team and to monitor new governance proposals.
Notifications on discord and/or by email are a good step.

Though I'm still worried that notification fatigue over time would cause us to stop paying attention which could have a disastrous effect. Not sure how to best mitigate this. Some ideas:
 - Make it a mandatory agenda item in the weekly to review all active proposals (but that's not enough since I think the proposal voting period is under a week, at 5 days)
 - Have a rotation in our team (and with some volunteers in the community?) for reviewing every single new proposal
 - Any other ideas?

**Comment by joshfraser** [comment]
We should require a high enough quarum that the odds of an attacker getting enough votes without widespread support is highly unlikely.

**Comment by franckc** [comment]
We decided to raise the quorum.
I'll create a separate issue for tracking governance+timelock monitoring.
